esphome:
  name: esphome-trovis
  friendly_name: ESPHome Trovis 5573 Adapter
  name_add_mac_suffix: true

esp32:
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG
  logs:
    modbus.controller: DEBUG
    modbus.transport: DEBUG

ota:
  - platform: esphome
